//! Living in the menu bar.
//!
//! Dictation is a background feature — you press the globe key while you're in
//! Slack, or a browser, or a terminal, and the app you're dictating *into* is
//! never this one. So the window is incidental: closing it should put the app
//! away, not shut the engine down and take the hotkey with it.
//!
//! The Dock icon is deliberately kept (no `LSUIElement`). A pure menu-bar agent
//! is right for something that is only a hotkey, but this app also has a real
//! reading and history UI, and hiding it from the Dock and from Cmd-Tab would
//! make that half of the product hard to get back to.

use tauri::menu::{CheckMenuItem, Menu, MenuItem, PredefinedMenuItem};
use tauri::tray::{MouseButton, MouseButtonState, TrayIconBuilder, TrayIconEvent};
use tauri::{AppHandle, Manager, Window};
use tauri_plugin_autostart::ManagerExt;

/// The menu-bar mark: the brand cells on transparency, no tile.
///
/// It has to be a separate asset from the app icon. macOS template images carry
/// no colour — the system reads the *alpha* and redraws the shape in black or
/// white to suit the menu bar. The app icon's tile is fully opaque, so every
/// pixel of it counts as shape and the menu bar renders a solid white blob
/// rather than a small app icon. Generated by `scripts/make-icons.sh`.
const TRAY_ICON: &[u8] = include_bytes!("../icons/tray.png");

/// Bring the main window back, creating focus as if the user had launched it.
pub fn show_main(app: &AppHandle) {
    if let Some(win) = app.get_webview_window("main") {
        let _ = win.show();
        let _ = win.unminimize();
        let _ = win.set_focus();
    }
}

/// Close means hide.
///
/// Returning true tells the caller to swallow the close. Without this, closing
/// the window would exit the process, and the globe key would quietly stop
/// working — the single most confusing way for a background app to fail.
pub fn hide_instead_of_quit(win: &Window) -> bool {
    let _ = win.hide();
    true
}

/// Put the most recent transcript back on the clipboard.
///
/// Dictation pastes for you and then hands the clipboard back to whatever was
/// on it, so the words you just spoke are only in the app. That is the right
/// default and it is also the moment you notice the paste went somewhere you
/// didn't mean, or landed in a field that ate it. This is the way back, and it
/// is in the menu bar because that is reachable without leaving the app you are
/// standing in.
fn copy_last(app: &AppHandle) {
    let store = app.state::<crate::store::Store>();
    let found = store
        .0
        .lock()
        .map_err(|e| e.to_string())
        .and_then(|conn| crate::store::latest(&conn).map_err(|e| e.to_string()));

    match found {
        // An empty library is not a failure — there is simply nothing to put
        // back, and someone with no notes is not the one clicking this.
        Ok(None) => {}
        Ok(Some((title, text))) => match crate::clipboard::write(&text) {
            Ok(()) => eprintln!("[tray] copied \"{title}\" to the clipboard"),
            Err(e) => eprintln!("[tray] could not copy \"{title}\": {e}"),
        },
        Err(e) => eprintln!("[tray] could not read the last transcript: {e}"),
    }
}

pub fn install_tray(app: &AppHandle) -> tauri::Result<()> {
    let autostart = app.autolaunch();
    let launching = autostart.is_enabled().unwrap_or(false);

    let open = MenuItem::with_id(app, "open", "Open VoiceDumps", true, None::<&str>)?;
    // Sits with Open rather than in its own group: both are things you came to
    // the menu to *do*, as against the settings below the rule.
    let copy = MenuItem::with_id(
        app,
        "copy-last",
        "Copy Last Transcript",
        true,
        None::<&str>,
    )?;
    let login = CheckMenuItem::with_id(
        app,
        "login",
        "Launch at Login",
        true,
        launching,
        None::<&str>,
    )?;
    let quit = MenuItem::with_id(app, "quit", "Quit VoiceDumps", true, None::<&str>)?;
    let menu = Menu::with_items(
        app,
        &[
            &open,
            &copy,
            &PredefinedMenuItem::separator(app)?,
            &login,
            &PredefinedMenuItem::separator(app)?,
            &quit,
        ],
    )?;

    TrayIconBuilder::with_id("main")
        .icon(tauri::image::Image::from_bytes(TRAY_ICON)?)
        // Let macOS tint the mark for light and dark menu bars. This is only
        // safe because TRAY_ICON is a template: see the comment on it.
        .icon_as_template(true)
        .tooltip("VoiceDumps — press the globe key to dictate")
        .menu(&menu)
        .show_menu_on_left_click(false)
        .on_menu_event(move |app, event| match event.id().as_ref() {
            "open" => show_main(app),
            "copy-last" => copy_last(app),
            "login" => {
                let auto = app.autolaunch();
                let now = auto.is_enabled().unwrap_or(false);
                let _ = if now { auto.disable() } else { auto.enable() };
            }
            "quit" => app.exit(0),
            _ => {}
        })
        .on_tray_icon_event(|tray, event| {
            // Left click reopens; the menu is on right click. Matches how
            // menu-bar utilities behave, so it needs no explanation.
            if let TrayIconEvent::Click {
                button: MouseButton::Left,
                button_state: MouseButtonState::Up,
                ..
            } = event
            {
                show_main(tray.app_handle());
            }
        })
        .build(app)?;

    Ok(())
}
